config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :all_posts, only: [:index, :create]
  # respond_to :html, :js

  def new
    @post = Post.new
    respond_to do |format|
      format.html
      format.js {render layout: false}
    end
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js {render layout: false}
      else
        format.html { render :new }
        format.js {render layout: false}
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.js {render layout: false}
      else
        format.html { render :edit }
        format.js {render layout: false}
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def all_posts
    @posts = Post.all
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoticeRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, id: 'posts-form') do |form| %>
  <div class="form-group">
    <%= form.label :title%>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>">
  <div class="row">
    <div class="col-md-2">
      Title
    </div>
    <div class="col-md-6">
      Content
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= post.title %>
    </div>
    <div class="col-md-6">
      <%= post.content %>
    </div>
  </div>
  <%= link_to "Edit", edit_post_path(post), class:'btn btn-default', remote: true %>
</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
  document.querySelector('#post-form').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "shared/validation-messages", object: @post) %>');
<% else %>
  document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
  document.querySelector('#posts').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @post) %>') ;
  document.querySelector('#posts-form').reset();
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
document.querySelector('#post-<%= @post.id %>').remove();
document.getElementById('post-form').innerHTML = ("<%= j (render 'form', post: @post) %>");

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-5 offset-md-1">
    <h2>Posts</h2>
  </div>

  <div class="col-md-2 offset-md-4">
    <%= link_to 'New', new_post_path, class: "btn btn-default", remote: true %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 offset-md-2 " id='post-form'>
  </div>
</div>

<div class="row">
  <div class="col-md-7 offset-md-1" id='posts'>
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/new.js.erb
document.getElementById('post-form').innerHTML = ("<%= j (render 'form', post: @post) %>");

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/update.js.erb
<% if @post.errors.any? %>
  document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
  document.querySelector('#post-form').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render "shared/validation-messages", object: @post) %>');
<% else %>
  document.querySelector('#error_explanation') ? document.querySelector('#error_explanation').remove() : null ;
  document.querySelector('#posts').insertAdjacentHTML('afterbegin', '<%= escape_javascript(render @post) %>') ;
  document.querySelector('#posts-form').remove();
<% end %>

app/views/shared/_validation-messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>